feat:공지 수정 API
GAMZA-BAT/ALGOHUB-SERVER pull request #117
Opened 2024-10-07 15:14 UTC by s-hwan

## 📌 Related Issue
#110 
## 🚀 Description
- 공지 수정 API를 추가했습니다

## 📢 Review Point
- 권한 검증할 때 고민이 있었습니다..
- 1. 수정하려는 유저가 일치하지 않는 경우만 검증 
- 2. 스터디 그룹이 존재하는지 또한 그룹의 멤버인지검증 
- 현재 2번의 경우로 수정 권한 검증을 했는데 2번의 경우까지 검증하면 자연스럽게 게시글 작성자가 아니게 된다고 생각했습니다

## 📚Etc (선택)
-1번의 권한 검증이 낫다고 생각하시는지
-2번의 경우에서 제가 생각하지 못한 경우가 있을지 걱정이 됩니다 여러분 도와주세오!

2024-10-08 13:00 UTC, rladmstn requested changes
review point 질문 주신 내용은 지금처럼 2번 경우만 처리하면 1번을 커버할 수 없습니다.
현재처럼 1. 스터디 그룹이 존재하는지, 2. 게시글이 존재하는지, 3. 그룹 참여를 했는지
위 세가지 경우에 대해서만 처리하게 되면 작성자 아닌 사람이 수정할 수도 있게 됩니다. 더구나 방장/부방장만 관리할 수 있는 공지를 일반 멤버(PARTICIPANT)가 수정 가능하게 되겠죠!
 따라서 정확하게 현재 공지 수정을 요청한 user가 Board의 author와 일치하는지 검증 추가는 필수입니다. 
 이 부분과 코멘트 단 부분 반영해주시면 될 것 같습니다!

2024-10-08 13:00 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +	public ResponseEntity<String> updateBoard(@AuthedUser User user, @Valid @RequestBody UpdateBoardRequest request) {
request 검증 에러에 대한 처리 부분이 빠져있네요 추가해주세요-!

2024-10-28 12:08 UTC, s-hwan commented
@rladmstn 코멘트 반영 무려 3주 걸렸네요 죄송함다... ㅜ

2024-10-29 08:31 UTC, rladmstn commented
> @rladmstn 코멘트 반영 무려 3주 걸렸네요 죄송함다... ㅜ

<img width="219" alt="image" src="https://github.com/user-attachments/assets/73fc057b-c661-4459-8903-c9866a83c447">
오메 근데 커밋메세지에 저거 뭔가요..?

2024-10-29 08:37 UTC, rladmstn reviewed
게시글 수정인데 문제 수정 실패 에러 메세지가 무엇인가요!!!

2024-10-29 08:37 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +		return ResponseEntity.ok().body("OK");
요거 황교수님이 `ResponseEntity<String>` 리턴타입 void로 수정하셨으니 이번 PR에서도 return body 없애시죠!

2024-10-29 08:37 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +			throw new UserValidationException("문제를 수정할 수 있는 권한이 없습니다");
문제?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!

2024-10-29 08:38 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +			throw new UserValidationException("문제를 수정할 수 있는 권한이 없습니다");
제가 정신이 없었나봅니다... 수정 할게요 ㅠㅠ

2024-10-29 08:38 UTC, s-hwan commented
> > @rladmstn 코멘트 반영 무려 3주 걸렸네요 죄송함다... ㅜ
> 
> <img alt="image" width="219" src="https://private-user-images.githubusercontent.com/88280787/381042450-73fc057b-c661-4459-8903-c9866a83c447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTEzNjQsIm5iZiI6MTczMDE5MTA2NCwicGF0aCI6Ii84ODI4MDc4Ny8zODEwNDI0NTAtNzNmYzA1N2ItYzY2MS00NDU5LTg5MDMtYzk4NjZhODNjNDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4Mzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzNhNjljMjU1ZWVmMjY0ZjUxMDk2NDQyNzA0Y2Y2MjdmMjY4Y2JkNTFkOTkxYzU4ZDYxZmQ4Y2U4OGY3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.34B1Sc1cBkDkwKlghyWyx-5I7jOsIqjIKArVnXI74vg"> 오메 근데 커밋메세지에 저거 뭔가요..?

엥 이거 뭐지...................................

2024-10-29 14:12 UTC, rladmstn approved these changes
굿입니다-!

2024-10-29 14:29 UTC, sh0723 approved these changes
고생많으셨슴다 ~!~!

2024-10-29 14:30 UTC, sh0723 approved these changes

2024-10-29 14:30 UTC, merged