refactor : User desc 필드 추가
GAMZA-BAT/ALGOHUB-SERVER pull request #135
Opened 2024-10-27 09:49 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/algohub-server/issues/134

## 🚀 Description
- user entitiy에 desc필드 추가
- user 정보 조회에 desc추가
- user 정보 수정에 desc 추가

## 📢 Review Point
- user desc에 대한 정보가 쓰이는 곳들이 정보 조회, 정보 수정 말고 없다고 생각해서 이 두 부분만 수정했습니다!
- 만약 추가적으로 쓰이는 곳이 있다면 피드백해주세요!

## 📚Etc (선택)
- 회원가입할 때에는 user desc에 대한 정보를 넣지 않기 때문에 클라이언트에 null값을 주면 안될거같아서 "" 로 초기화 시켜놨는데 굳이 필요없는 일인가요 ..?

2024-10-27 11:14 UTC, hwangjokim requested changes
리뷰이전인데, 현재 쓰고있는 포매터가 설정이 이상한것같아요. 포매팅 설정 차이로 인한 diff가 엄청 잡혔네요 
https://github.com/GAMZA-BAT/algohub-server/pull/45
위 pr 참조해서 포매터 적용하고, 파일들 다시 포매팅해서 push 부탁드립니다

2024-10-29 08:39 UTC, rladmstn commented
포매터 적용하시면 리뷰하겟슴니다-

2024-10-29 12:53 UTC, hwangjokim commented
포매터가 먹다가 말았어용
<img width="447" alt="image" src="https://github.com/user-attachments/assets/21b85dd6-c989-4dab-9524-14ea480b77e3">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/d89ddb2e-31fb-4274-b713-fc42895c3fe9">
다음 과정 거쳐주세요

2024-10-29 12:59 UTC, sh0723 commented
> 포매터가 먹다가 말았어용 <img alt="image" width="447" src="https://private-user-images.githubusercontent.com/96808859/381129310-21b85dd6-c989-4dab-9524-14ea480b77e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDY5MTYsIm5iZiI6MTczMDIwNjYxNiwicGF0aCI6Ii85NjgwODg1OS8zODExMjkzMTAtMjFiODVkZDYtYzk4OS00ZGFiLTk1MjQtMTRlYTQ4MGI3N2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEyNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNjcxODRjMjY4MWQ4MTM3Yzg2YjAxNWMwZGNmZDg4Y2YwMDA5ZDJiOWQ4MTk2ZjU3NjUxNmJmYWZhZjZkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WDY2p6yoCRfYS6dXkeVPYOmK4cY92j33izkB7iKvurA"> <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/96808859/381129381-d89ddb2e-31fb-4274-b713-fc42895c3fe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDY5MTYsIm5iZiI6MTczMDIwNjYxNiwicGF0aCI6Ii85NjgwODg1OS8zODExMjkzODEtZDg5ZGRiMmUtMzFmYi00Mjc0LWI3MTMtZmM0Mjg5NWMzZmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEyNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OGY0NDA2ZmRhZmM0NzFjMGNmYzIzZWZlYTJjNDQzMGZkZjFhNjg5MzBkN2U2MDNkMmRlZjcxY2VkNGQxNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S8LkDV64gh-KspDSpkK08lG0GpkBsI5sxDooSMk3Ap0"> 다음 과정 거쳐주세요

감사함다..! 적용했어요

2024-10-29 13:05 UTC, hwangjokim commented
옙 :) 코멘트로 달았던 파일 전체 적용은 앞으로 매번 할 일은 없을거고, 지금처럼 포매터가 깨진 상태에서 이미 파일 여러개를 수정했다거나  할 때 수행하면 됩니다

2024-10-29 13:13 UTC, sh0723 commented
> 옙 :) 코멘트로 달았던 파일 전체 적용은 앞으로 매번 할 일은 없을거고, 지금처럼 포매터가 깨진 상태에서 이미 파일 여러개를 수정했다거나 할 때 수행하면 됩니다

네넵! 감사함다

2024-10-29 14:22 UTC, rladmstn requested changes
전체적으로 어디는 description이고 어디는 desc 인 것 같아요 축약어 없이 description 하나도 통일해주시면 좋을 듯 합니다! 축약어는 웬만하면 사용 안하는게 좋은지라..! 요 부분만 바꿔주심 다 좋슴니다

그리고 본문 질문 주신건.. 흠 그러게요 프론트에서 null 처리가 뭐 다를지 잘 모르겠네욥 저는 지금처럼 ""로 초기화 하는 것도 좋다고 생각합니담

2024-10-29 14:28 UTC, sh0723 commented
> 전체적으로 어디는 description이고 어디는 desc 인 것 같아요 축약어 없이 description 하나도 통일해주시면 좋을 듯 합니다! 축약어는 웬만하면 사용 안하는게 좋은지라..! 요 부분만 바꿔주심 다 좋슴니다
> 
> 그리고 본문 질문 주신건.. 흠 그러게요 프론트에서 null 처리가 뭐 다를지 잘 모르겠네욥 저는 지금처럼 ""로 초기화 하는 것도 좋다고 생각합니담

반영했습니다!

"" 이건 그럼 그대로 냅둘게요 ㅎ.ㅎ

2024-10-30 01:20 UTC, hwangjokim approved these changes

2024-10-30 01:20 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/domain/User.java
> +	private String description = "";
무조건 초기화해줘서 널이 아니니까, DB상에서 NotNull이여야 함을 보장해주세요.
이 필드 위에 '@Column' 어노테이션 이용하면 할 수 있어요.

2024-11-01 06:12 UTC, rladmstn approved these changes
굳

2024-11-02 08:42 UTC, hwangjokim commented
그.. @Column만 쓰면 아무 효과가 없고, nullable=false를 써주거나, @NotNull 어노테이션을 붙여야합니다

2024-11-05 14:10 UTC, s-hwan approved these changes
황조가 말한 
 nullable=false를 써주거나, @NotNull 어노테이션을 붙여야합니다 만 해결해주세요!

2024-11-05 14:10 UTC, sh0723 commented
> 황조가 말한 nullable=false를 써주거나, @NotNull 어노테이션을 붙여야합니다 만 해결해주세요!

이거 했어요~!

2024-11-05 14:11 UTC, sh0723 commented
> 황조가 말한 nullable=false를 써주거나, @NotNull 어노테이션을 붙여야합니다 만 해결해주세요!

네엡~!

2024-11-05 14:35 UTC, hwangjokim commented
요거 한줄 반영하면 좋으니 오늘 반영하고 머지 ㄱㄱ하죠~

2024-11-05 15:09 UTC, merged

2024-11-05 15:19 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/domain/User.java
> +	private String description = "";
두개를넣으셨네용
담에 하나 빼주세요~