feat : 다른 유저 정보 조회 API 추가
GAMZA-BAT/ALGOHUB-SERVER pull request #158
Opened 2024-11-09 08:43 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/algohub-server/issues/152

## 🚀 Description
- 하나의 api에 user( desc, email, bjNick)등등 과 해당 user가 속한 그룹리스트에 대한 정보를 담는건 크고 코드 재사용성도 떨어지는 것으로 판단되어 두개로 쪼개서 api를 만들었습니다.

## 📢 Review Point
- 기존의 코드들을 최대한 재사용해서 만들었는데 혹시 고쳐야하는 부분 있으면 말해주세요!

## 📚Etc (선택)

2024-11-09 14:55 UTC, s-hwan approved these changes
굿굿👍👍

2024-11-11 13:39 UTC, rladmstn requested changes
수고하셨어요!! 코멘트 고려 부탁합니다-!

2024-11-11 13:39 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
> +	@GetMapping(value = "other-user-group_list")
엔드포인트에 이상한 언더바가 끼워져있어요..!

그리고 이 부분은 `@PathVariable`을 사용하는게 더 좋아보여요! 모르신다면 찾아보길 권장드립니다
Github도 url 보면 사용자 닉네임 들어가듯이 `/api/{userId}/group` 뭐 이런식으로 쓰이는건데 이 API에서는 이런식의 엔드포인트가 더 적절하지 않을까 싶습니담

2024-11-11 13:39 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
> +	@Operation(summary = "그룹 목록 조회 API", description = "방장 여부 상관 없이 유저가 참여하고 있는 그룹 모두 조회")
[nit] Swagger summary가 위에 현재 유저의 그룹 목록 조회랑 겹칩니다.
로직상 문제는 없지만 프론트 배려를 위해 더 정확한 메세지로 명시해줍시다!

2024-11-11 13:39 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
> +	public GetStudyGroupListsResponse getOtherStudyGroupList(Long targetUserId) {
이거 뭔가 내 그룹 목록 조회 메소드랑 중복이 많아서 조회 메소드를 하나로 빼서 재사용하는 리팩토링 할 수 있을 것 같은데..

2024-11-13 05:07 UTC, hwangjokim reviewed
아 리뷰 해놓고 서브밋 안함;;

2024-11-13 05:07 UTC, hwangjokim commented on build.gradle
> +    annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"
QueryDSL 이미 바로 위쪽에 선언되어있어요

2024-11-13 05:07 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
> +	@GetMapping(value = "other-user-group_list")
underscore(_) 말고 dash(-)로 써주세요. 혼용되어있어요

2024-11-13 05:07 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
> +	@Operation(summary = "그룹 목록 조회 API", description = "방장 여부 상관 없이 유저가 참여하고 있는 그룹 모두 조회")
operation 설명이 list랑 완전히 동일한데, 수정해주세요

2024-11-13 05:07 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
> +	public ResponseEntity<UserInfoResponse> OtherUserInfo(@AuthedUser User user, @RequestParam Long targetUserId) {
함수명은 동사형으로 써주세요

2024-11-13 07:48 UTC, hwangjokim commented on build.gradle
> +    annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"
덜 지워졌어요

2024-11-13 07:54 UTC, sh0723 commented
피드백 다 반영했슴다~

2024-11-13 08:17 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
> +	@GetMapping(value = "otheruser-info")
얘도 PathVariable 사용하면 더 좋을 것 같아요-!

2024-11-13 08:17 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
> +	@GetMapping(value = "/{targetUserId}/list")
소사하지만 userId가 좋아보입니다!

2024-11-13 09:17 UTC, sh0723 commented
다시 반영 해 놨슴다~!

2024-11-13 09:21 UTC, rladmstn approved these changes
LGTM-

2024-11-13 12:28 UTC, hwangjokim approved these changes
Conflict resolve 하고 머지해주세요~~

2024-11-14 14:09 UTC, merged