Feat/#24
GAMZA-BAT/ALGOHUB-SERVER pull request #25
Opened 2024-08-15 17:10 UTC by s-hwan

## 📌 Related Issue
#24  
## 🚀 Description
댓글 수정 가능 API를 추가했습니다

## 📢 Review Point
원래 댓글 작성한 user 만 수정할 수 있게 검증한번 해보려고 해서 
ModifyCommentReuqest에 User를 받아오려고 했는데 
1. User 정보를 전부 다 가져오는거더라구요..? <- 이게 원래 맞는건가...싶은...
2. 프론트 단에서 User의 Comment 만 수정할 수 있게 거를 수 있는지..? 궁금하구요..
3. Comment 에서 따로 userId를 들고 있는데 이거로 검증을 할 수 있는지....?

## 📚Etc (선택)
1. 궁금한 점 하나 더..! Comment 도메인에 setter를 추가해버렸는데 괜찮은 문제인지

2024-08-15 18:43 UTC, hwangjokim requested changes
1. User 정보를 전부 다 가져오는거더라구요..? <- 이게 원래 맞는건가...싶은...
이것 컨트롤러들 보면 어노테이션 통해서, API 호출한 유저를 주입받는 부분이 있습니다. 그것 참고 부탁드려요
2. 프론트 단에서 User의 Comment 만 수정할 수 있게 거를 수 있는지..? 궁금하구요..
뷰 상으로야 할 수 있지만, 이건 충분히 어뷰징할 수 있어요. 백엔드단에서 검증하지 않으면 누구나 어뷰징해서 남의 댓글을 수정해버리게 됩니다.
3. Comment 에서 따로 userId를 들고 있는데 이거로 검증을 할 수 있는지....?
정확히는 우린 스프링을 쓰고있으니 User 객체를 들고있는거고, 이것으로 검증하면 됩니다. 다른 기능 수정 구현된 컨트롤러/서비스쪽 코드 참고하면 될 것으로 예상됩니다 (내가 보진 않음)

2024-08-15 18:43 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	@PostMapping("/modify")
[blocker] RestFul API를 위해, "행위"를 URL에 묘사하지 말고, "자원"을 URL에 표기한뒤 HTTP METHOD를 통해 행위를 구분해주세요.
이 경우엔 기본 url이 `/api/comment`니까, 그냥 `@PutMapping`만 달아주는게 예시입니다.
다른 API도 보면, URL엔 자원을 표기하고 Post, Get, Delete, Put같은 Method를 통해 API의 행위를 구분하는것을 볼 수 있습니다.

2024-08-15 18:43 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	public ResponseEntity<Object> modifyComment(@Valid @RequestBody ModifyCommentRequest request, Errors errors){
이것 String으로 "OK' 리턴하게 되어있는데, Object 말고 String으로 쓰면 안돌아가나요?

2024-08-15 18:43 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +	public void setContent(String content) {
[blocker] Setter가 도메인에 있으면 안 좋은 이유는 은수가 설명해줬나요? 
setter는 'set' 자체로는 어떤 행위를 하고싶은지 알 수 없는 문제가 있습니다.
예를 들어, 이 `setContent` 메서드를 호출하는게
처음 Comment 객체를 새로 만들어서 Content를 채워주는것인지, 아니면 업데이트를 하고싶은것인지 알 수가 없습니다. 이는 코드 가독성을 저하시키고, 휴먼 에러 가능성을 올립니다.
제가 제안하는건, `setContent와` `setCreatedAt은` 어짜피 항상 같이 불리니까, 도메인 안에 `updateComment`같은 메서드를 만들고, content와 ceatedAt을 받아서 setter처럼 업데이트 해주는 (this.content = content ... 식으로) 메서드를 만들면 명확히 업데이트시에 사용하는 메서드임을 알 수 있을 것 같아요.

2024-08-15 18:43 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
> +
[blocker] 가장 중요한 본인 댓글인지 유효성 검사하는 파트가 빠져있네요. comment 도메인에, user 정보도 들고있으니 댓글 객체에서 작성자를 찾을 수 있고, 컨트롤러에서 AuthUser를 들고오면 API를 호출한사람이 누군지도 알 수 있네요. 그 User를 서비스에 파라미터로 넘겨줘서, 둘이 일치하는 과정이 있어야 합니다.

2024-08-15 18:46 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
> +		commentRepository.save(comment);
[major] 그리고, 업데이트는 save가 아니라 JPA에 있는 Dirty Checking이라는 기능을 적극 이용하는 코드를 쓰면 좋을 것 같아요.
Dirty Checking으로 Update하는것의 개념은..
https://jojoldu.tistory.com/415
https://everydayyy.tistory.com/157

내부 용어가 좀 어려울 수 있는데, 이해 안되는 것 바로바로 질문해주세요

2024-08-16 09:22 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	public ResponseEntity<Object> modifyComment(@Valid @RequestBody ModifyCommentRequest request, Errors errors){
해보겠읍니다..! 근데 전반적으로 이 컨트롤러의 동작 방식이 이해가 잘 안되는데요 
이게 프론트에서 요청을 dto에 담아서 Controller 로 날리는건가요? 그런 후에 service에서 메소드 실행을 하고 프론트에 return을 ResponeEntitiy에 담아 보내는 과정이 맞는지 굼금합니다

2024-08-16 09:24 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	@PostMapping("/modify")
확인했습니다.. 근데 PostMapping PutMapping 이 여러개 있는경우에는 따로 URL에 써줘야 하는거 같은데 그 경우는 어떤 식으로 표기해줘야하나요?!

2024-08-16 12:53 UTC, s-hwan commented
테스트 코드 작성해보려했는데 쉽지 않더군요... 일단 피드백 반영해서 커밋했습니다.

2024-08-16 13:22 UTC, rladmstn requested changes
review point에 대한 답변은 교수님께서 잘해주셨기에,,

2024-08-16 13:22 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +@DynamicUpdate
요게 붙는 이유는 뭘까요?? 기존 JPA dirty checking이랑 무슨 차이인지 궁금합니담 처음보는데 진짜 몰라서 질문해요,,

2024-08-16 13:22 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +	public void upadateComment(String content,LocalDateTime createdAt) {
필드가 createdAt이면 댓글이 처음 작성된 시점을 의미한다고 생각합니다! 저는 수정된 날짜를 표현할거면 createdAt을 수정하기 보단 updatedAt 필드를 따로 갱신해줘야 한다고 생각하는데 어떨까요??

2024-08-16 13:25 UTC, hwangjokim commented
카톡에도 써놨지만, 기록차 남깁니다

Resolved 버튼은 코멘트를 단 사람이 누르는 것으로 하고, Change request를 리뷰어가 달았을 경우엔 코멘트 반영 이후 Re-request 버튼을 눌러주세요!

2024-08-16 14:06 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +		this.createdAt = LocalDateTime.now();
그리고 요것도 파라미터에 createdAt을 받는데 실제 update 로직에선 안쓰이네요! 필요 없는 파라미터는 제거해줍시다

2024-08-16 14:40 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +@DynamicUpdate
기존 JPA dirty checking 은 필드 하나만 수정되어도 모든 필드를 update 하는 쿼리를 날린다고 합니다..!
DynamicUpdate 어노테이션 붙이면 수정된 필드 하나만 update하는 쿼리를 날린다고 해서 붙였습니다
없어도 되긴 하는 것 같아요!

2024-08-16 14:41 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +	public void upadateComment(String content,LocalDateTime createdAt) {
반영하겠습니다!

2024-08-17 08:42 UTC, hwangjokim approved these changes
수고하셨습니다

2024-08-17 08:42 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	@PostMapping("/modify")
여러개인 경우엔 URL로 구분해줘야 하는 것 맞고, api에 맞게 적절하게 네이밍 지어주면 됩니다!

2024-08-17 08:42 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	public ResponseEntity<Object> modifyComment(@Valid @RequestBody ModifyCommentRequest request, Errors errors){
1. 컨트롤러는 DTO 필드 스키마에 맞게, JSON 형태로 API를 호출합니다. 이것을 컨트롤러가 받습니다
2. JSON 형태로 날아온 것들, @RequestBody가 붙은 DTO와 필드를 비교해 일치하면 객체로 만들어줍니다.
3. 서비스 메서드를 통해 로직을 수행하고, Return값을 받습니다.
4. 프론트에 "OK" 라는 문자열과 함께, HTTP STATUS CODE 200을 리턴합니다

2024-08-17 08:42 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
> +			throw new UserValidationException("댓글 작성자가 아닙니다.");
@rladmstn 이거 조금 저도 헷갈리는데, @AuthedUser로 주입받은 User도 영속성 컨텍스트의 범위 안에 들어오나요? 맞다면 getId.equals 없이, 그냥 단순 동등성 비교로도 해결이 될 것 같아서요

2024-08-17 08:42 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
> +		Comment comment = commentRepository.findById(request.commentId())
[nit] 이렇게 하고, 밑에서 `comment.user` 를 호출하면 Lazy Loading에 의해 DB에 쿼리가 한번 더 날아갑니다. 가능하면 User까지 fetch-join을 통해 가져오면 좋겠지만 생각해보니 SQL을 아직 할 줄 모르는군요..

2024-08-17 09:08 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
> +			throw new UserValidationException("댓글 작성자가 아닙니다.");
영속성 범위가 아니라서 equals로 해야 비교 가능합니담

2024-08-17 09:14 UTC, rladmstn approved these changes
성장추 드립니다!

2024-08-17 09:14 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +@DynamicUpdate
쿼리최적화? 느낌이군요! 정보 좋와요

2024-08-17 12:40 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
> +			throw new UserValidationException("댓글 작성자가 아닙니다.");
아.. OSIV땜에 될수도 있나 했는데 아닌가보네요 ㅎㅎ

2024-08-17 14:05 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +	public ResponseEntity<Object> modifyComment(@Valid @RequestBody ModifyCommentRequest request, Errors errors){
> 1. 컨트롤러는 DTO 필드 스키마에 맞게, JSON 형태로 API를 호출합니다. 이것을 컨트롤러가 받습니다
> 2. JSON 형태로 날아온 것들, `@RequestBody` 가 붙은 DTO와 필드를 비교해 일치하면 객체로 만들어줍니다.
> 3. 서비스 메서드를 통해 로직을 수행하고, Return값을 받습니다.
> 4. 프론트에 "OK" 라는 문자열과 함께, HTTP STATUS CODE 200을 리턴합니다

지식 +1 감사합니다

2024-08-18 07:28 UTC, sh0723 approved these changes

2024-08-18 07:28 UTC, merged