test:댓글API 테스트 작성
GAMZA-BAT/ALGOHUB-SERVER pull request #50
Opened 2024-08-21 07:30 UTC by s-hwan

## 📌 Related Issue
#42 

## 🚀 Description
-댓글 수정 test코드를 작성해봤습니다

## 📢 Review Point
- 테스트 코드 너무 어려워요 .. 맞는지 모르겠네여

## 📚Etc (선택)
- 테스트 통과는 하는데.. 이게 테스트 코드 로직이 이상해서 그냥 늘 통과하는 건지 그런거는 어떻게 검증하나요..?

2024-08-21 09:22 UTC, rladmstn requested changes
사실 테스트 코드는.. 공백으로 내도 통과하기 때문에 본인이 꼼꼼하게 짜는 수밖에 없다고 개인적으로 생각합니다 모든 경우의 수를 쪼개보고 꼼꼼하게 테코 만드는 연습을 합시다! 코멘트 드린 곳들에 검증 코드 추가 해주세요!

그리고 전에 댓글 수정 API PR 올리셨을 때 제가 createdAt을 수정하는 대신 updatedAt 필드 만들어서 수정 날짜를 갱신하는 건 어떻겠냐는 의견을 드렸었는데 혹시 반영이 안된걸까요?? 어떻게 되는건지 알려주세요!

2024-08-21 09:22 UTC, rladmstn commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +			.hasFieldOrPropertyWithValue("errors", "댓글 작성자가 아닙니다.");
댓글 수정 실패하는 경우의 수가 두가지 인거 같은데, 각 경우마다 테스트 코드를 작성해주세요! 고로 에러 객체가 무엇인지도 검증하는 부분이 필요합니다

2024-08-21 09:22 UTC, rladmstn commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +		assertEquals("Updated content", comment.getContent());
저희 댓글 수정할 때 댓글 생성 시간? 수정시간도 업데이트 되는 걸로 알고 있습니다 그 부분 검증이 없네요! 변경되는 모든 필드에 대해서는 검증을 붙여주시는 게 좋아요

2024-08-21 13:23 UTC, s-hwan commented
> 사실 테스트 코드는.. 공백으로 내도 통과하기 때문에 본인이 꼼꼼하게 짜는 수밖에 없다고 개인적으로 생각합니다 모든 경우의 수를 쪼개보고 꼼꼼하게 테코 만드는 연습을 합시다! 코멘트 드린 곳들에 검증 코드 추가 해주세요!
> 
> 그리고 전에 댓글 수정 API PR 올리셨을 때 제가 createdAt을 수정하는 대신 updatedAt 필드 만들어서 수정 날짜를 갱신하는 건 어떻겠냐는 의견을 드렸었는데 혹시 반영이 안된걸까요?? 어떻게 되는건지 알려주세요!

아 그 updateAt 이 메소드에서 매개변수로 받는데 사용은 안한다고 했을 때 그냥 updateAt이 필요하지 않다는 줄 이해해서 만들지 않았는데 지금 다시 글을 읽어보니 이해가 됐습니다 다시 반영하도록하겠습니다!

2024-08-21 14:07 UTC, hwangjo-v6x commented
https://github.com/GAMZA-BAT/ALGOHUB-SERVER/actions/runs/10491424371/job/29060524629

2024-08-21 14:20 UTC, s-hwan commented
> https://github.com/GAMZA-BAT/ALGOHUB-SERVER/actions/runs/10491424371/job/29060524629

ㅠㅠㅠㅠ다시 짜볼게여...

2024-08-21 14:27 UTC, s-hwan commented
시간 검증을 할 때 equals로 하면 안되는군요..

2024-08-21 14:31 UTC, hwangjokim commented
LocalDateTime의 정밀도는 마이크로초입니다. 그래서 Assert에서 updateAt과 LocalDateTime.now()로 비교하는 건 굉장히 나이브하고, 타이밍 이슈가 생길 가능성이 높습니다.

2024-08-21 14:40 UTC, s-hwan commented
> LocalDateTime의 정밀도는 마이크로초입니다. 그래서 Assert에서 updateAt과 LocalDateTime.now()로 비교하는 건 굉장히 나이브하고, 타이밍 이슈가 생길 가능성이 높습니다.

isCloseTo로 비교하는 방법도 문제가 생길 가능성이 높다는 말인가요?!

2024-08-21 16:00 UTC, hwangjokim commented
옙. pc 리소스를 많이 탑니다. 나이브한건 마찬가지여서, LocalDateTime.now()를 모킹해야 할 것 같아요

2024-08-22 06:12 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +	public void upadateComment(String content, LocalDateTime now) {
여기 now 안쓰는데 파라미터 있네요 ㅎㅎ

2024-08-22 06:12 UTC, rladmstn commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +			.hasFieldOrPropertyWithValue("errors", "댓글 작성자가 아닙니다.");
여기 아직 에러 객체 검증 코드 없어요!!

2024-08-22 06:12 UTC, rladmstn commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +			.containsExactly(HttpStatus.NOT_FOUND.value(), "존재하지 않는 댓글 입니다.");
[q] extracting이랑 containsExactly는 첨봤네용 containsExactly가 extracting의 순서대로 매핑돼서 검증되는건가요??

2024-08-22 15:24 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
> +	public void upadateComment(String content, LocalDateTime now) {
어이쿠 이게 뭐야 해결하겠습니다..

2024-08-22 15:29 UTC, s-hwan commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +			.containsExactly(HttpStatus.NOT_FOUND.value(), "존재하지 않는 댓글 입니다.");
CommentValidationException에서 extracting 메소드에서 code필드랑 error 필드를 뽑아낸 후 순서대로 HttpsStatus.NOT_FOUND.valure()와 "존재하지 않는 댓글 입니다" 와 같은지 containsExcatly메소드로 확인 하는 작업이라고 합니다..!

2024-08-22 15:30 UTC, hwangjokim requested changes
사실 테스트코드 + 바쁨 이슈로 제대로 못봄 ㅈㅅ

2024-08-22 15:30 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +		@Valid @RequestBody UpdateCommentRequest request, Errors errors) {
이 diff는 왜 생긴거예요? PR이랑 무관해보이는데..

2024-08-22 15:30 UTC, hwangjokim commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +	}
여기 시간검증 말한것처럼 나이브한것 고치기 위해
LocalDateTime.now()자체를 mockStatic 써서 모킹하거나 하는 등 방법으로 수정해주세요

2024-08-22 15:32 UTC, s-hwan commented
괜찮습니다.. 테코는 근데 진짜로 정신 나갈거같아요 너무 어려움 ..ㅠㅠㅠ

2024-08-22 15:38 UTC, s-hwan commented
황조님 피드백을 반영해봤읍니다..

2024-08-22 15:43 UTC, s-hwan commented
하하 테스트 통과를 못하네요 ^^

2024-08-22 15:43 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
> +		@Valid @RequestBody UpdateCommentRequest request, Errors errors) {
아 Modify 이름이 짜쳐서 바꿨읍니닫..

2024-08-22 15:44 UTC, s-hwan commented on src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
> +	}
이게 지금 보이네요 다시 해보겠습니다

2024-08-22 15:44 UTC, hwangjo-v6x commented
fail 났을 때 details 누르면 자세한 내용 볼 수 있어요
그리고 테스트코드 작업시에는 커밋/푸시 전 직접 한번 테스트 돌려보고 올리면 좀 더 좋구요
<img width="952" alt="image" src="https://github.com/user-attachments/assets/e6c41377-ca65-496b-9e11-09cb501354d6">

2024-08-22 16:32 UTC, s-hwan commented
테스트 코드 싫다..

2024-08-22 17:13 UTC, hwangjokim commented
어렵고 모를땐 톡방이나 이슈에 멘션걸고 그냥 무지성 질문 ㄱㄱ하시죠
아니면 그냥 어려운 내용을 이슈에 기록해도 좋구요
죽겠다고 티내야 주변에서 많이 붙어서 도와줍니다!

2024-08-22 17:14 UTC, s-hwan commented
> 어렵고 모를땐 톡방이나 이슈에 멘션걸고 그냥 무지성 질문 ㄱㄱ하시죠 아니면 그냥 어려운 내용을 이슈에 기록해도 좋구요 죽겠다고 티내야 주변에서 많이 붙어서 도와줍니다!

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ든든합니다 무지성 질문 가겠습니다

2024-08-23 06:30 UTC, rladmstn approved these changes
테코와의 사투.. 수고하셨습니다

2024-08-23 13:07 UTC, sh0723 approved these changes

2024-08-23 13:09 UTC, hwangjokim approved these changes
다른 두 분이 리뷰 잘 해줬을것이라 믿고 어프로브 합니다~

2024-08-23 13:10 UTC, merged