feat : 그룹멤버 Role추가
GAMZA-BAT/ALGOHUB-SERVER pull request #51
Opened 2024-08-21 07:30 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/ALGOHUB-SERVER/issues/49

## 🚀 Description
- studygroup 필드에 role 추가했고, 이에 따라 그룹참여 API도 role 추가해놨습니다. 

## 📢 Review Point
--

## 📚Etc (선택)
role을 String형으로 해놨고,  << participant , Administrator >>  처음 참여할 땐 participant로 들어오도록 구현해놨습니다.

2024-08-21 07:41 UTC, hwangjokim requested changes
[q] 제가 디비구조 잘 모르는데, owner는 GroupMember 도메인으로 안 들어가나요?

[blocker] Role같은 경우는 String 말고, Enum을 쓰는걸 권장합니다. String은 휴먼 에러 가능성도 높고, 실수해도 알아차리기가 너무 힘들어요. Enum을 필드에 쓰고,`@Enumerated(EnumType.STRING)` 옵션을 붙여주면 String으로 들어가요.

@rladmstn 그리고 User 테이블에 enum이 string처리가 안 되어서 Integer로 들어가는데, 이것 수정 부탁드립니다.

2024-08-21 07:47 UTC, sh0723 commented
[q] 제가 디비구조 잘 모르는데, owner는 GroupMember 도메인으로 안 들어가나요?
 -> [A] : 넵 owner은 GroupMember로 안들어가고 studyGroup도메인으로 들어갑니다. 
 
  [blocker] Role같은 경우는 String 말고, Enum을 쓰는걸 권장합니다. String은 휴먼 에러 가능성도 높고, 실수해도 알아차리기가 너무 힘들어요. Enum을 필드에 쓰고,@Enumerated(EnumType.STRING) 옵션을 붙여주면 String으로 들어가요.
  -> 넵! 수정하고 오겠읍니다 ㅎ.ㅎ

2024-08-21 08:06 UTC, rladmstn commented
> @rladmstn 그리고 User 테이블에 enum이 string처리가 안 되어서 Integer로 들어가는데, 이것 수정 부탁드립니다.

아 요걸 못봤네요 수정하겠습니다

2024-08-21 18:07 UTC, rladmstn commented
User 도메인에 Role이라는 이름의 enum이 이미 있는지라, GroupMember에 동일한 이름의 Role enum을 만들어버리면 나중에 멤버 역할 별 로직을 추가할 때 혼동이 있을 수 있습니다!
 물론 import를 잘 관리한다면 문제 없겠지만, 가독성과 역할 분리를 위해서는 웬만하면 같은 이름의 클래스나 Enum은 지양하는 것이 좋을 듯 합니다.

2024-08-22 09:01 UTC, sh0723 commented
은수랑 황조 피드백 모두 반영해놨습니다 확인하고 리뷰해주십쇼!

2024-08-22 09:10 UTC, rladmstn commented
> 은수랑 황조 피드백 모두 반영해놨습니다 확인하고 리뷰해주십쇼!

넴 수정사항 변경됐으면 Re-request 눌러주세욥

2024-08-22 09:14 UTC, sh0723 commented
> > 은수랑 황조 피드백 모두 반영해놨습니다 확인하고 리뷰해주십쇼!
> 
> 넴 수정사항 변경됐으면 Re-request 눌러주세욥

했습니다!

2024-08-22 09:18 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/studygroup/etc/RoleOfGroupMember.java
> +	public static RoleOfGroupMember fromValue(String value) {
[q] 근데 요거는 어디서 쓰일 메서드 인가요?? 제가 혹시 쓰이는 부분을 못찾은 걸까요..?

2024-08-22 09:20 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/studygroup/etc/RoleOfGroupMember.java
> +}
[q] 근데 요거는 어디서 쓰일 메서드 인가요?? 제가 혹시 쓰이는 부분을 못찾은 걸까요..?

2024-08-22 10:10 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/studygroup/etc/RoleOfGroupMember.java
> +}
@sh0723 왜 없어졌나요?!!

2024-08-22 14:00 UTC, rladmstn approved these changes

2024-08-22 15:13 UTC, s-hwan approved these changes
잘 봤습니당.. 근데 사라진 InvalidRoleException 있으면 좋을 것 같아요..어디서 써도 쓸 듯

2024-08-22 15:26 UTC, hwangjokim approved these changes
LGTM

2024-08-22 15:26 UTC, hwangjokim commented
은수랑 승환이형이 메서드 왜 없어졌냐고 물어보는 코멘트 있어서 머지는 안 합니다.
@rladmstn @s-hwan

2024-08-22 16:08 UTC, merged

2024-08-22 16:19 UTC, sh0723 commented
> 은수랑 승환이형이 메서드 왜 없어졌냐고 물어보는 코멘트 있어서 머지는 안 합니다. @rladmstn @s-hwan

 저 메서드가 Role이 잘못들어왔을 때 에러나게 하는 코드고 저가 지피티 도움을 받고 한지라 ㅎㅎ..필요없을줄 알았는데 필요하다고 해서 다시 넣었습니다!