test : 그룸 멤버 전체 랭킹 API 테스트코드 추가
GAMZA-BAT/ALGOHUB-SERVER pull request #61
Opened 2024-08-22 15:40 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/ALGOHUB-SERVER/issues/52

## 🚀 Description
그룸 멤버 전체 랭킹 API 테스트코드를 만들어봤습니다

## 📢 Review Point
성공하는경우 , 그룹을 못찾아서 실패하는경우, 권한이 없어서 실패하는경우 세가지를 테스트 했습니다!

## 📚Etc (선택)
---

2024-08-22 17:17 UTC, rladmstn requested changes
테코를 꼼꼼히 쓰는 습관을 들입시다 화이팅

2024-08-22 17:17 UTC, rladmstn commented on src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
> +		assertThat((result.get(1).getRank())).isEqualTo(2);
테스트에서 2등을 user, 1등을 user2로 둔 것 같은데 단순히 rank만 검증하지 말고 response에 대한 웬만한 필드는 검증하는게 좋다고 생각해요 GetRankingResponse로 들어갈 내용이 rank만 있을게 아닐테니까요!

2024-08-22 17:18 UTC, hwangjo-v6x commented
테스트코드 뉴비절단기네

2024-08-22 17:18 UTC, hwangjokim commented
테스트코드 뉴비절단기네

2024-08-22 17:20 UTC, sh0723 commented on src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
> +		assertThat((result.get(1).getRank())).isEqualTo(2);
아아 사실 2위 1위 순서로 리스트에 넣은지라 중요한 함수인 정렬함수만 잘 돌아가면 된다고 생각해서 그렇게 했슴다.. 고칠게요!

2024-08-22 17:20 UTC, s-hwan commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ테코에서 다 Re-request받는게 개 슬프네 진짜로...ㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2024-08-22 17:21 UTC, hwangjokim commented
컨플릭 해결은 
1. develop으로 체크아웃합니다.
2. pull 해서 최신 코드를 가져옵니다.
3. 작업 브랜치로 다시 체크아웃 합니다.
4. git merge develop 해서, 컨플릭 나는걸 해소합니다.
5. 해소 후 git push해서 PR에 들어와 해소 되었는지 확인합니다.

2024-08-22 17:24 UTC, hwangjokim approved these changes
LGTM

2024-08-22 18:21 UTC, rladmstn approved these changes
피드백 반영이 확실하네요 수고하셧슴다-

2024-08-22 18:21 UTC, rladmstn commented on src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
> +		assertThat((result.get(1).getRank())).isEqualTo(2);
사실 저도 다 하는건 아닙니다만,, 그래도 어느정도 중요한 정보로 userNickname정도는? 해주면 좋지 않을까 싶네욥

2024-08-23 12:09 UTC, s-hwan approved these changes
남의 테스트 코드를 읽어보면서 점점 테코를 이해를 하고 있습니다.. 같이 고생해요 우리 ㅠ

2024-08-23 12:37 UTC, merged