feature : 그룹 Role 따라 타 API들에 권한 검증 코드 추가
GAMZA-BAT/ALGOHUB-SERVER pull request #67
Opened 2024-08-22 19:09 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/ALGOHUB-SERVER/issues/63

## 🚀 Description
-createProblem과 editProblem에 각각 부방장일 때에도 접근권한이 있도록 설정했슴다.

## 📢 Review Point
방장과 부방장을 모두 허용하는 코드부분이 좀 더럽습니다..ㅎㅎ 좀더 개선할 수 있는 부분이 있으면 말씀해주십쇼. 제 최선이었습니다

## 📚Etc (선택)
---

2024-08-23 01:29 UTC, hwangjokim requested changes
테스트코드 빼고 봤습니다. 코멘트 반영 부탁드리고 이해 안되는 부분은 질문 주세요

2024-08-23 01:29 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +				log.info("failed to send notification", e);
[q] 이거 히스토리 모르는데 이쪽 Exception은 왜 Exception e를 사용하며, @RestControllerAdvice에서 전역 처리 안 하나요?

2024-08-23 01:29 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +				log.info("success to create problem");
[blocker] 이 부분은 위에랑 코드가 사실상 복붙인데요. 다른 부분은 멤버 권한 검사정도 뿐인 것 같습니다. 
맨 위쪽에서 `!group.getOwner().getId().equals(user.getId()) && !groupMember.getRole().equals(RoleOfGroupMember.ADMIN)`이면 권한 없음 오류를 바로 던지고, 밑 부분 로직은 기존 것을 그대로 쓰면 될 것 같아요.

2024-08-23 01:29 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +					() -> new StudyGroupValidationException(HttpStatus.FORBIDDEN.value(), "문제에 대한 권한이 없습니다. : create"));
[major] 권한이 없는것도 맞는 말이지만, 이 경우는 그룹에 애초에 속하지 않은 경우니 에러 메세지를 조금 더 자세히 써주세요.

2024-08-23 01:29 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +				log.info("success to edit problem deadline");
여기도 마찬가지인데.. 권한 검사하는것을 모아서 한번에 하면 if문 한개만으로 모두 처리가 가능 할 것 같아요.

2024-08-23 06:23 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +				log.info("failed to send notification", e);
알림 전송 부분은 제가 추가 했던 곳인데요 알림 전송이 롤백 됐다고 문제 등록 API를 전체 롤백 하는 건 비즈니스 로직에서 옳지 않다고 판단해서 try-catch로 예외처리를 합니다
 그리고 이건 알림 구현이 프론트까지 정상적으로 연동되면 추가될 부분인데 예외 발생일 경우 알림 전송 안된 데이터 히스토리 모아서 알림 목록에 추가하는 처리가 필요해서 전역 처리는 안합니다
 아마 예외 객체는 저 부분이 구현될 때 구체화 되지 않을까 싶네요

2024-08-23 06:38 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +				log.info("failed to send notification", e);
아 옙 이해했습니다

2024-08-23 06:50 UTC, rladmstn requested changes
저도 황교수님과 비슷한 의견으로.. 권한 검증할 때 owner, role 두 단계 안나누고 하나의 if 문 안에서 모두 처리 할 수 있을 것 같아보여요 그게 깔끔할 것 같습니다.
그리고 문제 생성 성공 테스트코드는 잘 만들었는데 문제 수정 테코가 추가 안되어있네요! 문제 생성처럼 추가 기기합시다

2024-08-23 06:52 UTC, rladmstn commented
> 저도 황교수님과 비슷한 의견으로.. 권한 검증할 때 owner, role 두 단계 안나누고 하나의 if 문 안에서 모두 처리 할 수 있을 것 같아보여요 그게 깔끔할 것 같습니다. 그리고 문제 생성 성공 테스트코드는 잘 만들었는데 문제 수정 테코가 추가 안되어있네요! 문제 생성처럼 추가 기기합시다

2024-08-23 08:21 UTC, sh0723 commented
황조, 은수 피드백 다 반영해놨슴다 확인해주십숑

2024-08-23 08:23 UTC, sh0723 commented
아 테스트 코드 하나 빼먹었다 다시할게요

2024-08-23 08:33 UTC, sh0723 commented
@rladmstn @hwangjokim 피드백 반영 해놨슴다 !

2024-08-23 09:49 UTC, hwangjokim requested changes
조금만 더 개선해봅시다

2024-08-23 09:49 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +			throw new StudyGroupValidationException(HttpStatus.FORBIDDEN.value(), "문제에 대한 권한이 없습니다. : create");
[major] else에 throw하지 말고, 처음에 안될 조건 검사해서 바로 throw해주세요. 그러면 밑 부분은 indent없이 가져 갈 수 있습니다. (early return처럼) 가독성 문제입니다

2024-08-23 09:49 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +		if ((group.getOwner().getId().equals(user.getId()) && groupMember.isEmpty()) || (!groupMember.isEmpty()
조건이 많이 복잡해졌는데, &&로 묶인 조건 두개를 변수로 빼서 이름지어  if문 안에서 사용해주세요.

2024-08-23 11:15 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +			throw new StudyGroupValidationException(HttpStatus.FORBIDDEN.value(), "문제에 대한 권한이 없습니다. : create");
음 이건 어려운게,, 방장이 그룹멤버에 속해있지 않아서 만약 방장일 경우에는 부방장인 경우를 확인하는 코드에 걸리고, 부방장인경우 방장인 경우를 확인하는 코드에 걸려서 제가 저렇게 짰던거거든요 .. 아닐까요?

2024-08-23 11:16 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +			throw new StudyGroupValidationException(HttpStatus.FORBIDDEN.value(), "문제에 대한 권한이 없습니다. : create");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋif 순서랑 안에 넣는걸 어케해야할지 모르겠어

2024-08-23 11:16 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +		if ((group.getOwner().getId().equals(user.getId()) && groupMember.isEmpty()) || (!groupMember.isEmpty()
이건 적용하겠습니다!

2024-08-23 11:26 UTC, rladmstn requested changes
테코는 좋슴다 로직 부분 코드 좀만 더 깔끔했으면..!

2024-08-23 11:26 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +			throw new StudyGroupValidationException(HttpStatus.FORBIDDEN.value(), "문제에 대한 권한이 없습니다. : create");
현재의 if랑 else를 반대로 생각하면 되지 않나요? 조건에 맞지 않는 경우를 if로 거르면서 에러 throw 하면 될 것 같단 생각이 드는디요

2024-08-23 11:30 UTC, sh0723 commented
> 테코는 좋슴다 로직 부분 코드 좀만 더 깔끔했으면..!

저게 보면.. if문 안이 좀 복잡해서 하나가 통과되면 하나에 걸리고 이런게 많더라고요.. 그래서 그렇게 빼니까 테스트코드에서 에러가납니다ㅠ.ㅠ

2024-08-23 11:30 UTC, sh0723 commented
> 테코는 좋슴다 로직 부분 코드 좀만 더 깔끔했으면..!

아 근데 다시 해보고올게요 ㅎ.ㅎ

2024-08-23 11:34 UTC, rladmstn commented
> > 테코는 좋슴다 로직 부분 코드 좀만 더 깔끔했으면..!
> 
> 저게 보면.. if문 안이 좀 복잡해서 하나가 통과되면 하나에 걸리고 이런게 많더라고요.. 그래서 그렇게 빼니까 테스트코드에서 에러가납니다ㅠ.ㅠ

지금 검증 부분을 if문 한 번에 처리하려고 해서 그러는 것 같아요 권한 없는 경우도 여러 경우의 수가 있는만큼 에러처리도 한 번에 처리하지 말고 여러 번에 걸쳐서 할 수 있게 코드를 수정해줘야 가독성 높아질 것 같습니다

2024-08-23 11:38 UTC, sh0723 commented
피드백 반영 전부 다 했습니다! 확인해주세용

2024-08-23 11:41 UTC, rladmstn requested changes

2024-08-23 11:41 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +			throw new StudyGroupValidationException(HttpStatus.FORBIDDEN.value(), "문제에 대한 권한이 없습니다. : create");
문제에 접근할 수 없는 이유가 두 가지인데 권한 문제도 있고 그룹 참여자가 아닌 경우도 있지않나요? 테스트코드에서 나눴던 것 처럼 경우 쪼개서 에러 처리 해주세요
 에러 메세지도 경우 따라서 더 세부적으로 작성해주고 테스트 코드에서도 이 부분 반영해서 검증 해주셔야 할 것 같네요

2024-08-23 13:04 UTC, hwangjokim approved these changes
은수 코멘트 + 제 코멘트 반영부탁드립니다

2024-08-23 13:04 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +		if ((group.getOwner().getId().equals(user.getId()) && groupMember.isEmpty()) || (!groupMember.isEmpty()
조건 변수로 빼는거 여긴 빼먹으셨어요

2024-08-23 13:04 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
> +		} else {
여기도 else throw..

2024-08-23 13:26 UTC, sh0723 commented
피드백 다시 다 반영했슴다!

2024-08-23 14:01 UTC, rladmstn approved these changes
긴 여정 수고하셨어요,,

2024-08-23 18:33 UTC, hwangjokim approved these changes
수고많았습니다 :)

2024-08-24 13:17 UTC, s-hwan approved these changes
고생하셨습니다..

2024-08-24 13:18 UTC, merged