feat:공지 작성 API 추가 했습니다
GAMZA-BAT/ALGOHUB-SERVER pull request #69
Opened 2024-08-23 17:44 UTC by s-hwan

## 📌 Related Issue
#55 
## 🚀 Description
- 공지 작성 API를 추가하였습니다 

## 📢 Review Point
-  제가 새로운 entitiy는 처음 만들어 보는지라 .. 틀린 부분이 있다면 지적 해주시면 바로 수정하겠습니다

## 📚Etc (선택)
하 테스트 코드 테스트 할 때 서비스를 모킹하면 안된다는걸 이번에 알았읍니다 개같은거...! 
지식 +1 ..

2024-08-23 18:41 UTC, hwangjokim requested changes
단기간에 많이 성장한게 눈에 보입니다. 코멘트 확인 부탁드려요 🙂

2024-08-23 18:41 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
> +	@ManyToOne(fetch = FetchType.LAZY)
[nit] 매핑하는것들은, 매핑 아닌 필드들 밑에 써주세요. 암묵적 컨벤션..

2024-08-23 18:41 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
> +		this.updatedAt = null;
[nit] null 명시적으로 안 넣어도 돼요

2024-08-23 18:41 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		if (!studyGroup.getOwner().getId().equals(user.getId())) {
[q] 이건 스펙 질문인데, 오너만 쓸 수 있고 ADMIN은 못 쓰나요?

2024-08-23 18:41 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +	public void createBoard(@AuthedUser User user, CreateBoardRequest request) {
[blocker] `@Transactional`이 빠져있어요. 이러면 트랜잭션이 바뀌어서 제대로 작동 안 할것같음..

2024-08-23 18:41 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
> +	private User user;
[minor] 작성자를 뜻하는거면, user보단 author같은 명확한 이름을 사용 해 주세요.

2024-08-23 18:41 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
> +	private String content;
[major] 그냥 string쓰면 DB에서는 아마 VARCHAR(255)로 자료형이 잡힐텐데, 내용은 길어 질 수 있으니 @Column(columnDefinition = "TEXT") 같은거 써서 제한을 풀어주세요.

2024-08-23 18:41 UTC, hwangjokim commented on src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
> +	@Captor
[minor] 여기서 당장 안 쓰는 Mock된 의존성들 많은데 제거해주세요.

2024-08-23 18:44 UTC, rladmstn requested changes
첫트에 요정도면 굉장한 성장추 드립니다
코멘트 부분 적용해주시고 테스트 코드는 부방장인 경우 추가해서 작성해주세요!

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +	public ResponseEntity<String> createBoard(@AuthedUser User user, @Valid @RequestBody CreateBoardRequest request) {
[blocker] Request에 대해 @Valid를 붙였으면 요청을 검증하는 부분이 필요합니다 추가해주세요!

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
> +	private String content;
[major] 음 이건 당장은 문제로 나타나지 않을텐데, MySQL에서 String의 default 크기가 게시글의 본문 크기로 두기엔 좀 적습니다 함 찾아보시고 크기 수정 해보심 좋을 것 같아요

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardRequest.java
> +) {
[minor] 각 필드들에 대해 null일 경우 발생할 에러 메세지를 작성해주면 좋을 것 같슴다

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull Long StudyGroupId) {
CreateBoardRequest와 마찬가지!

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull Long StudyGroupId) {
근데 얘는 미리 만들어둔거죠?? 게시글 정보 가져오는 request DTO인거같은데

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +	public void createBoard(@AuthedUser User user, CreateBoardRequest request) {
[blocker] 혹시 트랜잭션이라는 개념을 아시나요? 서비스 계층에서 매우 중요한 개념인데 '@Transactional' 한번 찾아보시고 필요한 어노테이션 붙여주셔야할 것 같아요

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +
[nit] BoardService에 @Slf4j를 붙이신 김에 말해보자면,, 저는 서비스 계층에서 메서드 하나가 끝나는 부분에 log 찍는 걸 선호합니다 아무 기능 없는 부분이지만 나중에 백로그 확인할 때도 그렇고 저는 여러모로 요긴하게 보더라구요
 필수는 아니지만 요쯤에 로그 하나 찍어보는 것도 좋을 것 가타요

2024-08-23 18:44 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		}
[blocker] 게시글 작성 권한은 부방장도 있습니다! 수정해주세요

2024-08-23 18:45 UTC, hwangjokim commented
리뷰 오지게 겹쳤네
그만큼 중요한 부분이시란 뜻이죠~

2024-08-23 18:47 UTC, rladmstn commented
> 리뷰 오지게 겹쳤네 그만큼 중요한 부분이시란 뜻이죠~

동시다발적 리뷰 이슈

2024-08-23 18:51 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull Long StudyGroupId) {
[blocker] 지금봤는데 카멜케이스.. 이거 안지켜지면 api 호출 제대로 안돼요

2024-08-23 18:52 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +
사실 이거 throw하는곳에도 다 붙여주긴 해야함

주요로직 성공 파트에도 찍어줘야하고..

2024-08-24 04:59 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
> +		this.updatedAt = null;
오 그렇군요..!

2024-08-24 05:06 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		if (!studyGroup.getOwner().getId().equals(user.getId())) {
ADMIN이 저희 같은 ALGOHUB 운영자들을 말하는거겠죠?
지금 user의 role 이 있고 groupMember에 role 이 있는데.. 좀 헷갈리네요

2024-08-24 05:14 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull Long StudyGroupId) {
조회 작업 하려고 만들어 뒀었읍니다.. 카멜케이스로 수정하겠습니다

2024-08-24 05:14 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +	public void createBoard(@AuthedUser User user, CreateBoardRequest request) {
넵 공부하겠습니다

2024-08-24 05:17 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		}
[q] User의 role 에 있는 ADMIN과 USER와 RoleOfGroupMember의 ADMIN과 PARTICIPANT 
이 둘의 ADMIN은 차이가 있는건가요..?

2024-08-24 05:17 UTC, s-hwan commented
두 분 친절한 리뷰 감사드립니다

2024-08-24 05:55 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		}
User 자체의 Role은
ㄹㅇ 전 시스템적인 권한입니다 (사이트 운영자 느낌) 
로그인 할 때 쓰는 Security에서 Role을 요구해서 넣은것이고, 현재 이를 명시적으로 활용하진 않습니다
그룹멤버 어드민은 우리가 원하는 부방장이에요

2024-08-24 05:56 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		}
넵 이름이 같아서 좀 헷갈리긴 할텐데 User에서는 우리같은 관리자를 맗는거고 RoleOfGroupMember에선 부방장이에요 공지는 부방장도 쓸 수 있게 해야합니다

2024-08-24 06:01 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		}
일단 알겠습니다..!

2024-08-24 12:44 UTC, hwangjokim approved these changes
수고하셨습니다

2024-08-24 12:44 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardRequest.java
> +								 @NotNull(message = "제목은 필수 입력입니다") String title,
[nit] Validation에서 `@NotNull` 과 `@NotBlank` 가 어떤 차이인지 알고 적절히 쓰면 좋을것같아용

2024-08-24 13:07 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardRequest.java
> +								 @NotNull(message = "제목은 필수 입력입니다") String title,
알아보고 수정 마지막으로 해보겠습니다!

2024-08-24 13:07 UTC, rladmstn approved these changes
수고하셧슴다

2024-08-24 13:07 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull(message = "그룹 id는 필수 입니다") Long studyGroupId) {
이거는 공지 작성 API 관련된 request가 아니라 blocker는 안걸겠습니다만 GetBoardRequest에서 그룹 id는 필요 없습니다! 이유 한번 생각해보시길 ㅎㅎ

2024-08-24 13:12 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull(message = "그룹 id는 필수 입니다") Long studyGroupId) {
그렇군요..! board에 그룹 id 가 있기 때문일까요?!

2024-08-24 13:14 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull(message = "그룹 id는 필수 입니다") Long studyGroupId) {
마자요 join으로 가져올 수 있는 정보라면 웬만해선 request로 받지 말고 매핑 정보 이용해서 가져오도록 합시담

2024-08-24 13:18 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
> +							  @NotNull(message = "그룹 id는 필수 입니다") Long studyGroupId) {
> 마자요 join으로 가져올 수 있는 정보라면 웬만해선 request로 받지 말고 매핑 정보 이용해서 가져오도록 합시담

넵 지식 +1 감사합니다

2024-08-24 14:45 UTC, sh0723 approved these changes
고생하셨슴다..

2024-08-24 14:45 UTC, merged