Feature/18
GAMZA-BAT/ALGOHUB-SERVER pull request #83
Opened 2024-08-27 16:13 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/ALGOHUB-SERVER/issues/18

## 🚀 Description
풀이리스트 가져올 때 // 유저 닉네임, 언어,세분화된 결과 // 로 필터링해서 가져오도록 했습니다~!

## 📢 Review Point
지피티한테 물어보면서 했는데 레포지토리에서 함수를 따로 만들어 쿼리를 날릴 수 있는 방법이 있어서 그렇게 했습니다!

## 📚Etc (선택)

2024-08-27 17:25 UTC, hwangjokim commented
PR제목 수정해주시고, 레이블 다는거 잊지 말아주세요

2024-08-30 08:06 UTC, rladmstn requested changes
혹시 실제로 돌려보셨나요?? 제 로컬 DB에 테스트 solution들 만들어서 돌려보는데 필터링이 제대로 동작 안하는 것 같네요
서비스 계층 테스트 코드에서도 테스트 코드의 결과로 결국 setup 해둔 solution이 필터링 필요 없이 모든 solution이 나오는지라 필터링 검증은 제대로 안된 테스트 코드인거 같아요
테스트는 필터링이 작동하는지를 테스트 할 수 있는 코드로 만들어주세요 그래야 로직 검증이 될 듯 합니다
한 번 확인 부탁드립니다~

2024-08-30 08:06 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
> +	}
[q] 얘네는 아예 처음보는 방법인데 요거 작동 원리 설명해주실 수 있나요??
갠적으로는 Specification<>과 root, query, criteriaBuilder, predicates가 뭔지 궁금하네욥

2024-08-30 08:59 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
> +	}
> [q] 얘네는 아예 처음보는 방법인데 요거 작동 원리 설명해주실 수 있나요?? 갠적으로는 Specification<>과 root, query, criteriaBuilder, predicates가 뭔지 궁금하네욥

지피티의 도움을 받아가면서 처움 접했던거긴한데
- Specification<Solution> 이부분이 동적으로 쿼리를 만들도록 해주는 부분으로 여기서 criteriaBuilder를 사용할 수 있어 criteriaBuilder 는 predicate객체를 리턴해줍니다
- var predicate는 조건들을 연결하는 부분입니다. 이 부분에서 conjunction이 AND의 역할을 하고있고 //  disjunction이라면 OR의 역할을 합니다
- root는 검색하는 엔티티를 의미하는데 여기선 Problem임다
- query는 쿼리의 전반적인 부분을 제어하는데 사용하는데 현재는 사용하지 않고 있긴 하지만 굳이 지울 필요는 없다고 해서 지우진 않았습니다 

대충 제가 이해한거긴한데 더 깊은 내용까진 잘 모르겟네욥..

2024-08-30 09:00 UTC, sh0723 commented
> 혹시 실제로 돌려보셨나요?? 제 로컬 DB에 테스트 solution들 만들어서 돌려보는데 필터링이 제대로 동작 안하는 것 같네요 서비스 계층 테스트 코드에서도 테스트 코드의 결과로 결국 setup 해둔 solution이 필터링 필요 없이 모든 solution이 나오는지라 필터링 검증은 제대로 안된 테스트 코드인거 같아요 테스트는 필터링이 작동하는지를 테스트 할 수 있는 코드로 만들어주세요 그래야 로직 검증이 될 듯 합니다 한 번 확인 부탁드립니다~

음 테스트 코드를 제 기준으로 짜고 잘 돌아간다 생각해서 실제로 스웨거에선 안해봤는데 테스트코드를 더 수정해보겠슴다!

2024-08-30 13:07 UTC, hwangjokim commented
오늘 볼게요

2024-08-31 03:28 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
> +	}
JPQL을 쓰지 않는다는 가정 하에, 이쯤되면 QueryDSL 적용해할듯.. 쿼리 읽기가 빡세네요

2024-08-31 03:34 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
> +			}
이거 이해가 잘 안되는데 정확히 뭘 하는 코드인가요?
그리고 Repository로 result 넘겨서 like로 검색하던데 점은 또 무엇인지,, 궁금합니다
추가적으로 코드 자체도 다음처럼 쓰면 간결해져요.
```java
if (result != null) {
    results.add(result);
    if (result.equals("맞았습니다!!")) {
        results.add("점");
    }
}
```

2024-09-08 14:20 UTC, rladmstn requested changes
굉장한.. 고생을 하고 계셨었군요..
테스트 코드가 아직도 필터링 역할을 못하고 있어요. 제가 전에 말씀 드렸던건 세팅하는 Solution 리스트에 다양한 결과나 닉네임들을 넣고 그 중에서 필터링으로 조회하는 테스트를 작성해달라는 코멘트였습니다. 
 지금 코드가 여러모로 복잡성이 상당해가지고.. 이거 QueryDsl 사용하면 지금보다 훨씬 깔끔하게 만들 수 있을 것 같은데 SQL을 모르셔서.. 작업을 제가 이전받을지 고민중인데 혹시 QueryDsl로 동적 쿼리 생성하는걸 도전해보실래요? 아님 제가 작업 이전 받을까요?

2024-09-08 14:24 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
> +			}
왜 내말 무시해잉 ㅠ

2024-09-08 14:25 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
> +			}
ㅋㄱㅋㄱㅋㄱㅋㄱㅋㄱㅋㄱㅋㄱ아 이거 삭제해서 말 안했어

2024-09-08 14:25 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
> +			}
동적쿼리 만드는걸 포기하고 걍 노가다로 바꿔서 ㅎㅎ..

2024-09-08 14:26 UTC, sh0723 commented
> 굉장한.. 고생을 하고 계셨었군요.. 테스트 코드가 아직도 필터링 역할을 못하고 있어요. 제가 전에 말씀 드렸던건 세팅하는 Solution 리스트에 다양한 결과나 닉네임들을 넣고 그 중에서 필터링으로 조회하는 테스트를 작성해달라는 코멘트였습니다. 지금 코드가 여러모로 복잡성이 상당해가지고.. 이거 QueryDsl 사용하면 지금보다 훨씬 깔끔하게 만들 수 있을 것 같은데 SQL을 모르셔서.. 작업을 제가 이전받을지 고민중인데 혹시 QueryDsl로 동적 쿼리 생성하는걸 도전해보실래요? 아님 제가 작업 이전 받을까요?

….ㅜ.ㅜ 내 회심의 역작이었는데.. 많이 더럽긴 한거같긴합니다.. 사실 이거 제가 계속 잡으면 나머지 두개 PR을 빨리 처리 못할거같아서 혹시 이전받아주실수있을까욥..

2024-09-08 14:28 UTC, rladmstn commented
> > 굉장한.. 고생을 하고 계셨었군요.. 테스트 코드가 아직도 필터링 역할을 못하고 있어요. 제가 전에 말씀 드렸던건 세팅하는 Solution 리스트에 다양한 결과나 닉네임들을 넣고 그 중에서 필터링으로 조회하는 테스트를 작성해달라는 코멘트였습니다. 지금 코드가 여러모로 복잡성이 상당해가지고.. 이거 QueryDsl 사용하면 지금보다 훨씬 깔끔하게 만들 수 있을 것 같은데 SQL을 모르셔서.. 작업을 제가 이전받을지 고민중인데 혹시 QueryDsl로 동적 쿼리 생성하는걸 도전해보실래요? 아님 제가 작업 이전 받을까요?
> 
> ….ㅜ.ㅜ 내 회심의 역작이었는데.. 많이 더럽긴 한거같긴합니다.. 사실 이거 제가 계속 잡으면 나머지 두개 PR을 빨리 처리 못할거같아서 혹시 이전받아주실수있을까욥..

복잡성도 복잡성인데 저 코드로 로컬테스트 하니까 필터링이 잘안되네요..! 그럼 제가 작업 이어서 하겠습니다!

2024-09-08 14:29 UTC, rladmstn commented
> > 굉장한.. 고생을 하고 계셨었군요.. 테스트 코드가 아직도 필터링 역할을 못하고 있어요. 제가 전에 말씀 드렸던건 세팅하는 Solution 리스트에 다양한 결과나 닉네임들을 넣고 그 중에서 필터링으로 조회하는 테스트를 작성해달라는 코멘트였습니다. 지금 코드가 여러모로 복잡성이 상당해가지고.. 이거 QueryDsl 사용하면 지금보다 훨씬 깔끔하게 만들 수 있을 것 같은데 SQL을 모르셔서.. 작업을 제가 이전받을지 고민중인데 혹시 QueryDsl로 동적 쿼리 생성하는걸 도전해보실래요? 아님 제가 작업 이전 받을까요?
> 
> ….ㅜ.ㅜ 내 회심의 역작이었는데.. 많이 더럽긴 한거같긴합니다.. 사실 이거 제가 계속 잡으면 나머지 두개 PR을 빨리 처리 못할거같아서 혹시 이전받아주실수있을까욥..

굉장하게...고생하셨어요,,

2024-09-08 17:30 UTC, hwangjokim reviewed
고생한 티는 팍팍 나지만 지금 코드로는 머지는 못 할것 같음..ㅠㅠ 돌아갔다고 하더라도, 함수들이 너무 많고, 복잡하고, 읽는게 불가능..한 수준이여서 근시일내에 무조건 누군가 다시짜게 될 코드같아요. 수고하셨지만 아쉽게 되었습니다..... 
수고하셨습니다 은수가 봐주는 개선버전 나오면 그때 같이 돌아봐요

2024-09-09 04:53 UTC, sh0723 commented
> 고생한 티는 팍팍 나지만 지금 코드로는 머지는 못 할것 같음..ㅠㅠ 돌아갔다고 하더라도, 함수들이 너무 많고, 복잡하고, 읽는게 불가능..한 수준이여서 근시일내에 무조건 누군가 다시짜게 될 코드같아요. 수고하셨지만 아쉽게 되었습니다..... 수고하셨습니다 은수가 봐주는 개선버전 나오면 그때 같이 돌아봐요

넵....ㅜ.ㅜ

2024-09-09 04:53 UTC, sh0723 commented
> > > 굉장한.. 고생을 하고 계셨었군요.. 테스트 코드가 아직도 필터링 역할을 못하고 있어요. 제가 전에 말씀 드렸던건 세팅하는 Solution 리스트에 다양한 결과나 닉네임들을 넣고 그 중에서 필터링으로 조회하는 테스트를 작성해달라는 코멘트였습니다. 지금 코드가 여러모로 복잡성이 상당해가지고.. 이거 QueryDsl 사용하면 지금보다 훨씬 깔끔하게 만들 수 있을 것 같은데 SQL을 모르셔서.. 작업을 제가 이전받을지 고민중인데 혹시 QueryDsl로 동적 쿼리 생성하는걸 도전해보실래요? 아님 제가 작업 이전 받을까요?
> > 
> > 
> > ….ㅜ.ㅜ 내 회심의 역작이었는데.. 많이 더럽긴 한거같긴합니다.. 사실 이거 제가 계속 잡으면 나머지 두개 PR을 빨리 처리 못할거같아서 혹시 이전받아주실수있을까욥..
> 
> 굉장하게...고생하셨어요,,

감..사합니다..

2024-09-11 13:33 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
> +	}
이 부분은 페이지 수 등 페이지네이션 할 때 사용하는 부분으로, 조회한 모든 solution의 총 개수를 반환하는 쿼리입니다. 원래 QueryDsl에서 query.fetchCount() 기능을 제공 했었으나, 단순 개수 반환은 불필요한 반환이라고 판단해 deprecated 됐다고 하네요..

2024-09-11 13:34 UTC, rladmstn commented
PR 이전 받아서 작업하고 Description 써두었습니다 확인해주세요~

2024-09-13 07:00 UTC, hwangjokim reviewed
구경잘했습니다~

2024-09-13 07:00 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
> +		"AND s.result = '맞았습니다!!'")
장기적으로는 constant에 가야할것같아요

2024-09-13 07:00 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
> +		query = addResultFilter(result, query);
여기 query를 immutable하게 쓰고있는데, 조금 어색해요. 이거 파라미터로 넘겨서 return없이 그냥 수정만 하면 반영이 안 되나요?

2024-09-13 07:00 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
> +		if (result != null && !result.isBlank()) {
이부분은 if문 끌고가지 말고 query early return해줘도 좋을것같아요

2024-09-13 07:08 UTC, hwangjokim commented
그리고 스트링 검색에 대한 인덱스쪽에서
MySQL 5.7 이후부터 지원하는 FullText Search에 대해서도 알아보시면 좋을 것 같습니다.

150만건 넣은 데이터는 어디서 가져오신건가요? 
그리고 저희 db 생성후 직접적으로 인덱스 건 적이 없을 것 같은데, 인덱스로 성능향상 이점을 보기 위해서는 **인덱스를 직접 걸어주셔야 합니다.** 
JPA에서 아니면 어노테이션에서 indexes를 설정해줘야 하구요 

where절에 들어가는 칼럼들 모두 인덱스 거신 다음 재시도 해보실래요?

2024-09-13 07:59 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
> +		query = addResultFilter(result, query);
아 이 부분은 저도 나중에 다시 보고 어색하다 싶어서 수정했는데 푸시를 안했네요..! 로컬에 수정 되어있습니다 곧 푸시하겠습니다.

2024-09-13 08:11 UTC, rladmstn commented
> 그리고 스트링 검색에 대한 인덱스쪽에서 여담이지만 MySQL 5.7 이후부터 지원하는 FullText Search에 대해서도 알아보시면 좋을 것 같습니다.
> 
> 150만건 넣은 데이터는 어디서 가져오신건가요? 그리고 저희 db 생성후 직접적으로 인덱스 건 적이 없을 것 같은데, 인덱스로 성능향상 이점을 보기 위해서는 **인덱스를 직접 걸어주셔야 합니다.** JPA에서 할거면 어노테이션에서 indexes를 설정해줘야 하구요
> 
> where절에 들어가는 칼럼들 모두 인덱스 거신 다음 재시도 해보실래요? rds상 solution 테이블엔 pk ,fk만 인덱스가 걸려있네요. 인덱스는 show index from (table..)로 볼 수 있습니다. 카디널리티 얘기는 은수씨가 저보다 더 잘 알테니 패스..

FullText Search는 제가 저 실험 해본 후에 발견한 내용이라 반영하기까지 좀 더 공부가 필요할 것 같아요 ㅎㅎ 더 공부해보겠습니다!

일단 150만건은 기존에 천 몇개정도 solution 테스트 데이터를 생성해 둔 게 있었는데 그 내용들을 복사해서 불렸습니다.

그리고 인덱스의 경우 제가 테스트 할 때 로컬 DB에 생성해서 사용했었고, @Index를 사용 안한 이유는 저 result를 REVERSE로 만들어서 생성하는 인덱스의 경우 함수형 인덱스인지라 어노테이션을 사용한 처리가 안된다고 하더라구요. 그래서 직접 아래같이 쿼리를 날려서 solution 테이블에 인덱스를 생성했습니다.
```
ALTER TABLE solution ADD INDEX idx_result_reverse ((REVERSE(result)));
```
제가 잘못 설정한 부분이 있을까요?

그리고 where절에 들어가는 칼럼들 모두 인덱스를 걸어야 한다는게 무슨 의미일까요? 저 REVERSE(result)과 무관한 language나 nickname도 인덱스가 걸려야 한다는 의미일까요?? 

+ ) 인덱스 힌트를 사용해서 지정도 해봤는데 저 idx_result_reverse를 사용하질 않더라구요. DB 옵티마이저가 해당 인덱스를 사용하지 않아도 괜찮은 환경이다 싶으면 사용을 안한다던데 테스트 데이터 세팅이 문제인가 싶기도 하구요.. 아직 더 찾아보고 있긴 합니다.

2024-09-14 13:16 UTC, rladmstn commented
현재 추가적으로 테스트를 진행 중인데요, 데이터 분포가 너무 균일하면 인덱스를 불필요하게 여겨서 사용하지 않는다는 글을 봤었습니다. 그래서 반복적인 데이터 복사 insert가 저 index 사용을 안하는 이유일까 싶어 쌩 랜덤으로 Faker(대상혁)이라는 python 툴을 써서 랜덤 데이터 100만개를 로컬 데이터베이스로 삽입했습니다. 

랜덤으로 생성해도 전체 100만개 중 대략 20만개가 점수 형태의 result로 구성되었었고, 이게 점수 형태 result가 꽤 많은 비율을 차지해서인지.. 여전히 force index를 사용해서도 해당 reverse index를 사용하지 않았습니다. 사용이 안되는 이유가 뭔지 파악하는게 너무 어렵네요ㅜ

추가적으로 진행 상황 생기면 코멘트로 보고해보겠습니다-

2024-09-14 15:31 UTC, hwangjokim commented
아하. 고생많네요
새로 데이터 넣은 상황에서 인덱스인가? 조회하면 카디널리티 상대값 볼 수 있었는데,
그 값들도 궁금해요

2024-09-14 15:34 UTC, rladmstn commented
> 아하. 고생많네요 새로 데이터 넣은 상황에서 인덱스인가? 조회하면 카디널리티 상대값 볼 수 있었는데, 그 값들도 궁금해요

카디널리티는 현재 삽입된 데이터들 기준 대략 19만 정도 됩니다!

2024-09-14 15:34 UTC, hwangjokim commented
다른 인덱스들은 몇인가용?

2024-09-14 15:37 UTC, rladmstn commented
> 다른 인덱스들은 몇인가용?

language는 25, user_id는 4로 나타납니다 얘네는 애초에 데이터 삽입할 때 언어 수도 그렇고 회원 수도 몇개 생성 안한지라 낮네욥

2024-09-14 15:40 UTC, hwangjokim commented
아하.. 이상하긴 하네요. 19만이라는 극단적으로 높은 카디널리티면 힌트 안줘도 실행계획 조회시 무조건 타야할것같은데.. 뭔가 저희가 모르는 실수나 내부 동작이 있나? 싶기도하네요 

시간 되실 때 이거 이슈쪽에다가 
생성된 데이터 들어있는 DB 파일이랑, 사용한 쿼리 남겨주시겠어요? 저도 궁금해져서 한번 해보고싶어요

2024-09-14 15:44 UTC, rladmstn commented
> 아하.. 이상하긴 하네요. 19만이라는 극단적으로 높은 카디널리티면 힌트 안줘도 실행계획 조회시 무조건 타야할것같은데.. 뭔가 저희가 모르는 실수나 내부 동작이 있나? 싶기도하네요
> 
> 시간 되실 때 이거 이슈쪽에다가 생성된 데이터 들어있는 DB 파일이랑, 사용한 쿼리 남겨주시겠어요? 저도 궁금해져서 한번 해보고싶어요



> 아하.. 이상하긴 하네요. 19만이라는 극단적으로 높은 카디널리티면 힌트 안줘도 실행계획 조회시 무조건 타야할것같은데.. 뭔가 저희가 모르는 실수나 내부 동작이 있나? 싶기도하네요
> 
> 시간 되실 때 이거 이슈쪽에다가 생성된 데이터 들어있는 DB 파일이랑, 사용한 쿼리 남겨주시겠어요? 저도 궁금해져서 한번 해보고싶어요

좋습니다 조만간 이슈에 올려두겠습니다!

2024-09-18 10:20 UTC, s-hwan approved these changes
모르는게 산더미에요 ㅠㅠ 고생하셨습니다..

2024-09-18 10:27 UTC, rladmstn commented
'맞았습니다!!' 조회 시 성능 문제가 아직까진 발견되지 않아 일단 이대로 진행하겠습니다. conflict 해결 후에 self-merge 하겠습니다!

2024-09-18 10:37 UTC, hwangjokim commented
예 일단 진행 블로킹 할건 아니니까 ㄱㄱ하시죠

2024-09-18 10:40 UTC, rladmstn approved these changes

2024-09-18 10:41 UTC, merged