feat : 비밀번호 변경 API 추가
GAMZA-BAT/ALGOHUB-SERVER pull request #90
Opened 2024-08-30 08:42 UTC by sh0723

## 📌 Related Issue
https://github.com/GAMZA-BAT/ALGOHUB-SERVER/issues/89

## 🚀 Description
- 현재의 비밀번호 검증 후 두번의 새로운 비밀번호 입력

## 📢 Review Point
- 새로운 비밀번호를 두번 작성하게 만들어서 확인하는 방식으로 만들었습니다. 이게 필요없을거같으면 말해주세요

## 📚Etc (선택)
---

2024-08-30 13:00 UTC, hwangjokim reviewed
수고하셨습니다.
암호화 잘 하고, 비교도 matches로 한 것 훌륭하네요

2024-08-30 13:00 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/dto/EditUserPasswordRequest.java
> +									  @NotBlank(message = "비밀번호는 필수 입력입니다.") String newPassword1,
비밀번호 두 번 입력하고 , 그 두개가 같은지 검증하는건 프론트엔드의 역할이라 하나만 해도 될것같아요.

2024-08-30 13:00 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
> +		userRepository.save(user);
JPA는 수정에 대해서는 save를 명시적으로 호출해주지 않아도 자동 저장이 되는데요, 이 기능은 Dirty Checking이라고 합니다. 한번 알아보면 좋을 것 같아요 🙂

2024-08-30 13:01 UTC, hwangjokim requested changes
실수로 submit했네요..^^
코멘트 확인해주시고, 왜 비밀번호는 해시함수로 암호화해서 저장해야 하는지까지 공부해보면 완벽할 것 같아요

2024-08-30 13:10 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/dto/EditUserPasswordRequest.java
> +									  @NotBlank(message = "비밀번호는 필수 입력입니다.") String newPassword1,
이게 왜 프론트엔드 역할인지 궁금하실까봐..

두 비밀번호가 같은지 검증하는건 사실 유저의 실수를 방지한다 차원입니다. 1차적인 입력값 필터링 (예를 들어 필수 항목을 빈 칸으로 제출한다던지..)은 프론트엔드가 해줘야하는데, API는 어뷰징 가능성도 있고, 엄밀해야 하기때문에 프론트엔드에게 크게 의존하지 않고 추가 검증하기도 하는겁니다.

그런데 유저가 비밀번호 두 개를 다르게 치는건 실수고, 프론트에서 필터링해줘도 됩니다.
만약 필터링되지 않았다고 하더라도, 로직상 어뷰징이나 보안적으로 크리티컬한 문제가 생기진 않습니다. 유저 잘못이니까요. 그래서 이것까지 잡아주려는건 로직담당인 백엔드 입장에선 투머치..

2024-08-31 08:57 UTC, rladmstn requested changes
저도 새로운 비밀번호 확인은 프론트쪽에서 충분히 할 수 있는거라 생각해서 확인하는건 없어도 될 것 같습니다
그리고 보통 새로운 비밀번호가 기존 비밀번호와 같으면 비밀번호 변경을 블락하는데 이 로직도 서버쪽에서 안전차 추가되면 좋지 않을까 싶긴 합니다
코멘트 확인 부탁합니다~

2024-08-31 08:57 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
> +		@Valid @RequestBody EditUserPasswordRequest request) {
여기 request @Valid만 붙고 검증하는 코드 없어요~

2024-08-31 08:57 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
> +		userRepository.save(user);
사실 위 코드는 Dirty checking이 적용 안되는 상황이긴 합니다 ㅎㅎ 하지만 왜 안되는지, 어느 경우에 되는지 꼭 찾아보기!

2024-08-31 09:50 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
> +		userRepository.save(user);
아그러네 ㅎㅎ 무지성리뷰 ㅈㅅ

2024-09-02 09:05 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/user/dto/EditUserPasswordRequest.java
> +									  @NotBlank(message = "비밀번호는 필수 입력입니다.") String newPassword1,
아 알겠습니다!

2024-09-09 04:53 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
> +		userRepository.save(user);
아 Dirty checking이 안되는게 내가 로그인된 user를 끌고 와서 사용하는거라 영속성 상태가 아니기 때문인거가 맞나요?!!

2024-09-09 05:36 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
> +		userRepository.save(user);
넴 @AuthedUser로 컨트롤러에서 받아온 User 객체가 영속성 컨텍스트 범위 내가 아니어서 Dirty checking 사용이 안되는거 맞아요~

2024-09-10 07:22 UTC, rladmstn approved these changes
수고하셨습니다-

2024-09-11 01:20 UTC, sh0723 commented
이거 머지하려고 로컬에서 develop pull 하면 자꾸 이전버전으로 디벨롭이랑 머지가 됩니다 ㅜㅜㅜ 어떻게 해야해요?!

2024-09-11 01:22 UTC, hwangjokim commented
그러면 로컬 디벨롭이 최신 상태가 아닌겁니다
git fetch origin
git pull origin develop 먼저 하고 로컬에서 머지해보세요

2024-09-11 01:26 UTC, sh0723 commented
> 그러면 로컬 디벨롭이 최신 상태가 아닌겁니다 디벨롭 브랜치로 체크아웃하고 git fetch origin git pull origin develop 먼저 하고 로컬에서 머지해보세요



> 그러면 로컬 디벨롭이 최신 상태가 아닌겁니다 디벨롭 브랜치로 체크아웃하고 git fetch origin git pull origin develop 먼저 하고 로컬에서 머지해보세요



> 그러면 로컬 디벨롭이 최신 상태가 아닌겁니다 디벨롭 브랜치로 체크아웃하고 git fetch origin git pull origin develop 먼저 하고 로컬에서 머지해보세요

흠... 그래도 계속 전 버전으로 되네요. 뭐가 문제지..

2024-09-11 02:29 UTC, sh0723 commented
충돌 해결했읍니다 확인 부탁드려요

2024-09-11 04:23 UTC, rladmstn approved these changes
conflict 해결이니까 믿겠습니다 그리고 PR에 레이블 꼬박꼬박 달아주세요~

2024-09-11 12:03 UTC, sh0723 commented
> conflict 해결이니까 믿겠습니다 그리고 PR에 레이블 꼬박꼬박 달아주세요~

네넵

2024-09-11 14:10 UTC, sh0723 commented
이건데 혹시 뭐때문에 change requested 해놓으신거죠??

2024-09-11 14:11 UTC, hwangjokim approved these changes

2024-09-11 14:11 UTC, merged

2024-09-11 14:12 UTC, rladmstn commented
근데 이거 승환이형은 안본거 아니었나요??

2024-09-11 14:13 UTC, sh0723 commented
아???? 맞네 학교에서 봐달라고 아침에 말해놨어서

2024-09-11 14:13 UTC, sh0723 commented
본줄알고 ............. 죄송함다..

2024-09-11 14:14 UTC, sh0723 commented
conflict 다 해결했다고 신나서 머지해버렸네요

2024-09-11 14:18 UTC, s-hwan commented
ㅋㅋㅋㅋㅋ전에 조금 보긴 봤어용!

2024-09-11 14:19 UTC, s-hwan commented
제가 얼른 봤어야했는데 죄송함다...

2024-09-11 14:19 UTC, sh0723 commented
저도 .... 본거 확인하고 머지했어야했는데 죄송해유

2024-09-11 14:19 UTC, hwangjokim commented
ㅋㅋㅋ 원래 이런 실수 한번씩 꼭 합니다
또 하기 좋은 대표적 실수가 push하고 CI 빌드 안보고 머지하기..

2024-09-11 14:20 UTC, sh0723 commented
> ㅋㅋㅋ 원래 이런 실수 한번씩 꼭 합니다 또 하기 좋은 대표적 실수가 push하고 CI 빌드 안보고 머지하기..

그래서 꼭 푸시하기 전에 빌드하고 푸시하고있긴 함다 ㅎ.ㅎ

2024-09-11 14:20 UTC, s-hwan commented
> ㅋㅋㅋ 원래 이런 실수 한번씩 꼭 합니다 또 하기 좋은 대표적 실수가 push하고 CI 빌드 안보고 머지하기..

push 하고 좀 기다려야하는건가요?!

2024-09-11 14:22 UTC, hwangjokim commented
github에서 run-test 테스트 도는거 보고 하는게 좋죠. 만약 컴파일 에러나, 테스트 도는게 실패하는 코드가 디벨롭에 가면 배포도 오류나서 막힐테니..

2024-09-11 14:32 UTC, s-hwan commented
> github에서 run-test 테스트 도는거 보고 하는게 좋죠. 만약 컴파일 에러나, 테스트 도는게 실패하는 코드가 디벨롭에 가면 배포도 오류나서 막힐테니..

지식 +1 감사함니다