feat:공지 목록 조회API 추가
GAMZA-BAT/ALGOHUB-SERVER pull request #99
Opened 2024-09-06 06:56 UTC by s-hwan

## 📌 Related Issue
#96 
## 🚀 Description
-공지 목록을 조회하는 API 추가했습니다!

## 📢 Review Point
- 
## 📚Etc (선택)

2024-09-06 08:22 UTC, rladmstn requested changes
코멘트 확인 부탁합니다~

2024-09-06 08:22 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +	@GetMapping(value = "/boardList")
[major] REST API의 엔드포인트는 카멜케이스 사용 안합니다! 가독성 측면에서 케밥케이스라는걸 쓰는데 하이픈 사용해서 만듭니다 수정해주세요~

2024-09-06 08:22 UTC, rladmstn commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +			throw new GroupMemberValidationException(HttpStatus.BAD_REQUEST.value(), "참여하지 않은 스터디 그룹입니다");
[nit] 개인 생각인데 요기 예외 처리에서 status code로 FORBIDDEN 사용하면 어떨까요?! 클라이언트가 요청은 제대로 보냈지만 해당 리소스에 대한 접근 권한이 없을 때 사용하거든요 여기 상황에선 forbidden이 더 맞지 않을까 싶습니다!

2024-09-07 19:01 UTC, hwangjokim reviewed
수고하셨어요

2024-09-07 19:01 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +	public ResponseEntity<GetBoardResponse> getBoard(@AuthedUser User user, @RequestParam Long boardId) {
저는 이거 단건조회, 목록조회면 이렇게 가져가지 말고 

`@Getmapping` 기본을 다건조회로 하고, 단건 조회는 그 뒤에 Pathvariable을 붙이도록 쓰는게 자연스러운 것 같아요. 

/api/board 하면 리스트고, /api/board/321 하면 id가 321번인것을 받도록..

2024-09-07 19:01 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		Boolean isOwner = (studyGroup.getOwner().getId().equals(user.getId()) && groupMember.isEmpty());
[q] 여기서 `groupMember.isEmpty()`는 왜 필요한거예요?

2024-09-07 19:01 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +			throw new GroupMemberValidationException(HttpStatus.BAD_REQUEST.value(), "참여하지 않은 스터디 그룹입니다");
이거 저는 nit 말고 major로 같은 의견입니다..

2024-09-08 13:11 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		Boolean isOwner = (studyGroup.getOwner().getId().equals(user.getId()) && groupMember.isEmpty());
Owner인 경우는 groupMember에 포함이 안되어서 이렇게 했습니다 없어도 될 것 같긴한데 혹시 몰라서 넣어놨습니다

2024-09-08 13:11 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +			throw new GroupMemberValidationException(HttpStatus.BAD_REQUEST.value(), "참여하지 않은 스터디 그룹입니다");
수정하겠습니다..!

2024-09-08 13:12 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +	public ResponseEntity<GetBoardResponse> getBoard(@AuthedUser User user, @RequestParam Long boardId) {
방법을 몰라서.. 이번 pr 마무리하고 공부하고 새로 이슈 파서 해보겠습니다!

2024-09-10 07:18 UTC, rladmstn approved these changes
LGTM !

2024-09-10 09:25 UTC, hwangjokim commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		Boolean isOwner = (studyGroup.getOwner().getId().equals(user.getId()) && groupMember.isEmpty());
그럼빼주세용 불필요한 조건은 가독성을 저하시킵니다

2024-09-10 12:25 UTC, sh0723 commented on src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
> +	@GetMapping(value = "/boardList")
아 이게 케밥케이스였군요 .. 그냥 은수씨가 쓰길래 따라 썼는데 지식하나 얻어갑니다

2024-09-10 12:27 UTC, sh0723 approved these changes

2024-09-10 12:27 UTC, sh0723 commented
혹시 황조가 리뷰어에서 이제 빠진다했는데 그럼 황조 approve없이도 나머지 둘이 approve했다면 머지할까요?

2024-09-10 12:47 UTC, rladmstn commented
> 혹시 황조가 리뷰어에서 이제 빠진다했는데 그럼 황조 approve없이도 나머지 둘이 approve했다면 머지할까요?

넵 이젠 그럽시다

2024-09-10 12:48 UTC, hwangjokim commented
옙 전 이제 본문만 읽고 코드는 잘 안봅니다

2024-09-10 23:59 UTC, s-hwan commented on src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
> +		Boolean isOwner = (studyGroup.getOwner().getId().equals(user.getId()) && groupMember.isEmpty());
반영하겠습니다~!

2024-09-11 14:19 UTC, s-hwan commented
이것도 이제 머지할까요?!

2024-09-11 15:18 UTC, rladmstn commented
> 이것도 이제 머지할까요?!

합시다-

2024-09-13 01:06 UTC, merged